#!/usr/bin/env bash
# Bash script that display information about subdomains

text_1="The subdomain";
text_2="is a A record and points to";

if (("$#" == 1))
then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"
    do
        ip="$(dig "$1" | awk '/^[^\;]*[0-9]+\.[0-9]+\.[0-9.]+\.[0-9]+/ { print $5 }')";
        echo "$text_1 $subdomain $text_2 $ip";
    done
else
    ip="$(dig "$2"."$1" | awk '/^[^\;]*[0-9]+\.[0-9]+\.[0-9.]+\.[0-9]+/ { print $5 }')";
    echo "$text_1 $2 $text_2 $ip";
fi
