#!/usr/bin/env bash
# Not found page 404

# update
sudo apt update

if (("$(pgrep -c nginx)" == 0))  # checks if already installed
then
    sudo apt-get install nginx -y;
fi

echo "Ceci n'est pas une page" > /var/www/html/404.html;
echo "Hello World!" > /var/www/html/index.html;

nginx_config="server {
        listen 80 default_server;
        listen [::]:80;

        root /var/www/html;
        index index.html;

        server_name _;

        location / {
            try_files \$uri \$uri/ =404;
        }

        location /redirect_me {
            return 301 \"https://www.youtube.com/watch?v=QH2-TGUlwu4\";
        }

        error_page 404 /404.html;

        location /404.html {
            internal;
        }
}"


echo -e "$nginx_config" > /etc/nginx/sites-available/default;

sudo rm /etc/nginx/sites-enabled/default;
ln -s  /etc/nginx/sites-available/default /etc/nginx/sites-enabled/;


sudo service nginx restart;
