#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom
# header (on web-01 and web-02)

sudo apt-get update -y
sudo apt upgrade

if (("$(pgrep -c nginx)" == 0))
then
    sudo apt-get install nginx -y;
fi

sudo sed -i '16i\
        add_header X-Served-By $hostname;' /etc/nginx/nginx.conf

sudo service nginx restart
