#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server

sudo apt-get update
sudo apt-get upgrade -y


if (("$(pgrep -c haproxy)" == 0))
then
    sudo apt-get install haproxy -y
fi

haproxy_config='
global
    log /dev/log    local0
    log /dev/log    local1 notice
    stats timeout 30s
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    retries 3
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend my_traffics
    mode http
    bind 0:80
    default_backend my_servers

backend my_servers
    balance roundrobin
    server my_server_1 web-01.rashisky.tech:80 check
    server my_server_2 web-02.rashisky.tech:80 check
'

echo "$haproxy_config" > /etc/haproxy/haproxy.cfg

service haproxy restart
