#!/usr/bin/env bash
# MySQL backup

# Dump all database into backup.sql, $1 gives the password, 2> supress any warnings
# mysqldump -uroot -p"$1" --all-databases > backup.sql
if (mysqldump -uroot -p"$1" --all-databases --result-file='backup.sql' 2> /dev/null)
then
    echo "backup.sql";
    # File name with format: day-month-year.tar.gz
    file_name="$(date +%d-%m-%Y).tar.gz"

    # Compress backup.sql into file_name
    tar -czf "$file_name" backup.sql
fi
