#!/usr/bin/env bash
# displays a list of currently running processes. Requirements:
# Must show all processes, for all users (a), including those which might
# not have a TTY (x), (u) gives the user names
# displays in a user-oriented format
# show process heirarchy

# a - all users, u - map each process with its user
# x - including those without TTY (by default, non-current user has no TTY)
ps auxf
