#!/usr/bin/env bash
# Bash script that:
# creates the file '/var/run/myscript.pid' containing its PID
# displays "To infinity and beyond" indefinitely
# displays "I hate the kill comand" when receiving a SIGTERM signal
# displays "Y U no love me?!" when receiving a SIGINT signal
# deletes the file "/var/run/myscript.pid" and terminates itself when
# receiving a SIGQUIT or SIGTERM signal

#!/bin/bash

pidfile="/var/run/myscript.pid"

echo $$ > "$pidfile"

stop() {
    rm "$pidfile"
    exit
}

# Once trap has been defined for specific signal, it will always handle it
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap "stop" SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 1  # Add a small delay to avoid high CPU usage
done

