#!/usr/bin/env bash
# displays number from 1 to 100

value="$(seq 1 100)"
for i in $value
do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) = 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
