#!/usr/bin/env bash
# displays the content of the file /etc/passwd. It displays:
# username
# user id
# home directory path for the user
# must use the while loop

while read -r line
do
    cut -d":" -f 1,3,6 <<< "$line"
done < /etc/passwd

# OR
# while IFS=":" read -r f1 f2 f3 f4 f5 f6 f7
# do
#     echo "$f1:$f3:$f6"
# done < /etc/passwd
