#!/usr/bin/env bash
# Displays the visitor IP along with the HTTP status code from
# Apache log file
# Requirements:
# Format: IP HTTP_CODE (e.g 185.130.5.207 301)
# You must use "awk"
# You are not allowed to use "while, for , until and cut"

awk '{ print $1, $9}' /var/log/apache2/access.log
