#!/usr/bin/env bash
# Displays the visitor IP along with the HTTP status code from
# Apache log file (given)
# Requirements:
# Format: OCCURENTCE_NUMBER IP HTTP_CODE (e.g 185.130.5.207 301)
# You must use "awk"
# You are not allowed to use "while, for , until and cut"

# awk '{a[$1, $9, $10]++} END {for (i in a) print a[i], i}' < apache-access.log
# awk '{a[$1 " " $9]++} END {for (i in a) print a[i], i}' < apache-access.log | sort
awk '{a[$1 " " $9]++} END {for (i in a) print "    ", a[i], i | "sort -nr"}' < apache-access.log
