#!/usr/bin/env bash
# Displays "Best School" 10 times, but for the 9th iteration, displays "Best School" and then Hi on a new line using if and while loop only

x=0
while [ $x -lt 10 ]
do
    echo "Best School"
    if [ $x -eq 8 ]
    then
        echo "Hi"
    fi
    ((x++))
done
