#!/usr/bin/env bash
# Displays "Best School" 10 times, but for 9th iteration,
# displays "Best School and the Hi" on a new line using "while loop"
i=0
while ((i < 10))
do
    echo "Best School"
    if ((i == 8))  # if [ "$i" == 8 ]  OR if [[ "$i" -eq 8 ]]
    then
        echo "Hi"
    fi
    ((i++))
done
