#!/usr/bin/env bash
# Displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China fro the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
x=1
while ((x <= 20))
do
    case $x in
        5)
            echo "bad luck from China"
	    echo $x
            ;;
        10)
            echo "bad luck from Japan"
	    echo $x
            ;;
        18)
            echo "bad luck from Italy"
	    echo $x
            ;;
        *)
            echo $x
            ;;
    esac
    ((x++))
done
