#!/usr/bin/env bash
# Bash script that give information about the "school" file

if test -e "school"  # if [-e "school"]
then
    echo "school file exists"
    if [ -s "school" ]  # if test -s "school"
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f "school" ]  # if test -f "school"
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
