#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/etc/hosts.new
echo "8.8.8.8		facebook.com" >> ~/etc/hosts.new
cp -f ~/hosts.new /etc/hosts
