#!/usr/bin/env bash
# get Apache to run on the container and to return a
# page containing Hello Holberton when querying the root of it.
docker run -p 8080:80 -d -ti holbertonschool/265-0

docker exec -ti trusting_pascal /bin/bash

# start apache2
service apache2 start
