#!/usr/bin/env bash
# Nginx is running as the ngix user

# change user to "nginx"
# awk '/user/ { $2 = "nginx;" }1' /etc/nginx/nginx.conf > temp && mv temp /etc/nginx/nginx.conf
sed -i 's/user.*/user nginx;/' /etc/nginx/nginx.conf
# sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf

# Replace 'listen' with port 8080
# awk '/listen [^\[][0-9]*/ { $0 = "\tlisten 8080 default_server;"}1' /etc/nginx/sites-available/default > temp && mv temp /etc/nginx/sites-available/default
sed -i 's/80/8080/' /etc/nginx/sites-available/default


# kill apache2
pkill apache2

# Restart Nginx
sudo -u nginx service nginx start;
