#!/usr/bin/env bash
# Nginx is running as the ngix user
sed -i 's/user.*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart;
