#!/usr/bin/env bash
# Nginx is running as the ngix user
sed -i 's/user.*/user nginx;/' /etc/nginx/nginx.conf
sed -i '/listen/s/[0-9]\+/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start;
