#!/usr/bin/env bash
# update an application by gracefully terminating their workers
# and not their master

if (("$(pgrep -c gunicorn)"))
then
    # no_of_processes="$(("$(pgrep -c gunicorn)" - 1))"
    workers=("$(pgrep gunicorn | tail -n +2)");
    for worker in "${workers[@]}"
    do
        kill -TERM "${worker}"
    done
fi
