#!/usr/bin/env bash
# update an application by gracefully reloading or terminating
# their workers and not their master
# shellcheck disable=SC2207

if (("$(pgrep -c gunicorn)"))
then
    worker_processes=()
    worker_processes+=( $(pgrep gunicorn | tail -n +2) );
    for worker in "${worker_processes[@]}"
    do
        kill -TERM "$worker"
    done
fi
